import { StyleSheet } from 'react-native';
import { colors, radius, spacing, typography } from '../theme/colors';

export const homeStyles = StyleSheet.create({
  scroll: {
    flex: 1,
    backgroundColor: colors.background,
  },
  safeArea: {
    flex: 1,
    backgroundColor: colors.background,
  },
  container: {
    flexGrow: 1,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.lg,
    paddingBottom: spacing.xl,
    gap: spacing.lg,
  },
  loadingContainer: {
    flex: 1,
    backgroundColor: colors.background,
    alignItems: 'center',
    justifyContent: 'center',
  },
  loadingText: {
    color: colors.mutedForeground,
    fontSize: typography.body,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: spacing.md,
    alignItems: 'flex-start',
    flexWrap: 'wrap',
  },
  heading: {
    color: colors.primary,
    fontSize: typography.title,
    fontWeight: '700',
  },
  headingSubtitle: {
    color: colors.mutedForeground,
    marginTop: spacing.xs,
    fontSize: typography.small,
  },
  modeBadge: {
    marginTop: spacing.xs,
    alignSelf: 'flex-start',
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: colors.primary,
    backgroundColor: colors.secondary,
  },
  modeBadgeText: {
    color: colors.primary,
    fontWeight: '700',
    fontSize: typography.tiny,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  modeBadgeWarning: {
    borderColor: '#f59e0b',
    backgroundColor: '#f59e0b22',
  },
  modeBadgeDanger: {
    borderColor: colors.danger,
    backgroundColor: '#ef444422',
  },
  modeInfoText: {
    color: colors.mutedForeground,
    fontSize: typography.small,
  },
  headerActions: {
    flexDirection: 'row',
    gap: spacing.xs,
    flexWrap: 'wrap',
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  quickActions: {
    flexDirection: 'row',
    gap: spacing.md,
    flexWrap: 'wrap',
    width: '100%',
  },
  xpubSection: {
    width: '100%',
    marginTop: spacing.sm,
    padding: spacing.md,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.secondary,
    gap: spacing.xs,
  },
  xpubLabel: {
    color: colors.primary,
    fontSize: typography.small,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  xpubRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  xpubValue: {
    flex: 1,
    color: colors.foreground,
    fontSize: typography.small,
    fontFamily: 'monospace',
    backgroundColor: colors.muted,
    paddingVertical: spacing.xs,
    paddingHorizontal: spacing.sm,
    borderRadius: radius.sm,
  },
  xpubCopyButton: {
    paddingVertical: spacing.xs,
    paddingHorizontal: spacing.md,
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: colors.primary,
    backgroundColor: colors.primary,
  },
  xpubCopyButtonDisabled: {
    opacity: 0.6,
  },
  xpubCopyButtonText: {
    color: colors.primaryText,
    fontWeight: '600',
    fontSize: typography.small,
  },
  xpubCopyButtonTextDisabled: {
    color: colors.primaryText,
    opacity: 0.7,
  },
  xpubHint: {
    color: colors.mutedForeground,
    fontSize: typography.tiny,
  },
  addressBalancesSection: {
    width: '100%',
    marginTop: spacing.sm,
    padding: spacing.md,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.secondary,
    gap: spacing.sm,
  },
  addressBalancesTitle: {
    color: colors.primary,
    fontSize: typography.small,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  addressBalanceItem: {
    gap: spacing.xs,
    paddingVertical: spacing.sm,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  addressBalanceHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  addressBalanceLabel: {
    color: colors.foreground,
    fontSize: typography.small,
    fontWeight: '600',
  },
  addressBalanceValue: {
    color: colors.primary,
    fontSize: typography.small,
    fontWeight: '700',
  },
  addressBalanceAddress: {
    color: colors.mutedForeground,
    fontSize: typography.tiny,
  },
  addressBalancePending: {
    color: colors.danger,
    fontSize: typography.tiny,
  },
  addressBalanceLink: {
    marginTop: spacing.xs,
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    paddingVertical: spacing.xs,
    paddingHorizontal: spacing.sm,
    borderRadius: radius.sm,
    backgroundColor: colors.primary,
  },
  addressBalanceLinkText: {
    color: colors.primaryText,
    fontSize: typography.tiny,
    fontWeight: '600',
  },
  historyButton: {
    marginTop: spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    gap: spacing.sm,
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: '#504f4f85',
  },
  historyButtonDisabled: {
    opacity: 0.5,
  },
  historyButtonIcon: {
    marginRight: 0,
    color: '#ffffff9f',
  },
  historyButtonTextContainer: {
    flex: 1,
    alignItems: 'flex-start',
    gap: spacing.xs,
  
  },
  historyButtonTitle: {
    color: '#ffffffe1',
    fontWeight: '400',
    fontSize: typography.body,
  },
  historyButtonSubtitle: {
    color: colors.mutedForeground,
    fontSize: typography.tiny,
  },
  quickActionButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: spacing.md,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.secondary,
    minWidth: 140,
  },
  quickActionIcon: {
    marginRight: spacing.sm,
  },
  quickActionText: {
    color: colors.primaryText,
    fontSize: typography.body,
    fontWeight: '600',
  },
  quickActionButtonDisabled: {
    opacity: 0.6,
  },
  quickActionTextDisabled: {
    color: colors.mutedForeground,
  },
  quickActionTextSecondary: {
    color: colors.foreground,
    fontSize: typography.body,
    fontWeight: '600',
  },
  sendButton: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  receiveButton: {
    backgroundColor: '#035820ff',
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.85)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: spacing.lg,
  },
  modalCard: {
    width: '100%',
    maxHeight: '90%',
    backgroundColor: colors.secondary,
    borderRadius: radius.lg,
    padding: spacing.lg,
    alignItems: 'center',
    gap: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
  },
  modalTitle: {
    color: colors.primary,
    fontSize: typography.headline,
    fontWeight: '700',
  },
  qrScannerContainer: {
    width: '100%',
    aspectRatio: 1,
    borderRadius: radius.md,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: colors.primary,
  },
  qrScanner: {
    width: '100%',
    height: '100%',
  },
  qrScannerHint: {
    color: colors.mutedForeground,
    fontSize: typography.small,
    textAlign: 'center',
  },
  qrScannerCancel: {
    marginTop: spacing.sm,
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.lg,
    borderRadius: radius.md,
    backgroundColor: colors.muted,
    alignItems: 'center',
  },
  qrScannerCancelText: {
    color: colors.foreground,
    fontWeight: '600',
    fontSize: typography.small,
  },
  qrScannerFallback: {
    width: '100%',
    height: 240,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.background,
    alignItems: 'center',
    justifyContent: 'center',
    padding: spacing.md,
    gap: spacing.sm,
  },
  qrScannerFallbackText: {
    color: colors.mutedForeground,
    fontSize: typography.small,
    textAlign: 'center',
  },
  receiveModalQr: {
    width: '100%',
    maxWidth: 280,
    aspectRatio: 1,
    borderRadius: radius.sm,
    backgroundColor: colors.background,
  },
  psbtModalScroll: {
    width: '100%',
  },
  psbtModalContent: {
    width: '100%',
    alignItems: 'center',
    gap: spacing.md,
    paddingBottom: spacing.sm,
  },
  signModalScroll: {
    width: '100%',
  },
  signModalContent: {
    width: '100%',
    alignItems: 'center',
    gap: spacing.md,
    paddingBottom: spacing.md,
  },
  sendModalScroll: {
    width: '100%',
  },
  sendModalContent: {
    width: '100%',
    alignItems: 'center',
    gap: spacing.md,
    paddingBottom: spacing.md,
  },
  modalDragHandleContainer: {
    width: '100%',
    alignItems: 'center',
    paddingBottom: spacing.sm,
  },
  modalDragHandle: {
    width: 48,
    height: 4,
    borderRadius: 2,
    backgroundColor: colors.muted,
  },
  modalFallback: {
    color: colors.mutedForeground,
    textAlign: 'center',
    fontSize: typography.small,
  },
  modalAddress: {
    color: colors.foreground,
    fontSize: typography.small,
    textAlign: 'center',
    paddingHorizontal: spacing.sm,
  },
  modalHint: {
    color: colors.mutedForeground,
    fontSize: typography.tiny,
    textAlign: 'center',
    paddingHorizontal: spacing.sm,
  },
  pendingNotice: {
    marginTop: spacing.xs,
    color: colors.danger,
    fontSize: typography.tiny,
    textAlign: 'center',
  },
  sendModalOptions: {
    width: '100%',
    flexDirection: 'row',
    gap: spacing.sm,
  },
  modalOptionButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
    paddingVertical: spacing.sm,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.primary,
    backgroundColor: colors.primary,
  },
  modalOptionButtonDisabled: {
    opacity: 0.6,
  },
  modalOptionButtonText: {
    color: colors.primaryText,
    fontWeight: '600',
    fontSize: typography.small,
  },
  percentageRow: {
    width: '100%',
    flexDirection: 'row',
    gap: spacing.sm,
  },
  percentageButton: {
    flex: 1,
    paddingVertical: spacing.sm,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.secondary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  percentageButtonActive: {
    borderColor: colors.primary,
    backgroundColor: colors.primary,
  },
  percentageButtonDisabled: {
    opacity: 0.6,
  },
  percentageButtonText: {
    color: colors.foreground,
    fontWeight: '600',
    fontSize: typography.small,
  },
  percentageButtonTextActive: {
    color: colors.primaryText,
  },
  percentageButtonTextDisabled: {
    color: colors.mutedForeground,
  },
  feeOptionsRow: {
    width: '100%',
    flexDirection: 'row',
    gap: spacing.sm,
  },
  feeOptionButton: {
    flex: 1,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.secondary,
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.sm,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  feeOptionButtonActive: {
    borderColor: colors.primary,
    backgroundColor: colors.primary,
  },
  feeOptionText: {
    color: colors.foreground,
    fontWeight: '600',
    fontSize: typography.small,
  },
  feeOptionTextActive: {
    color: colors.primaryText,
  },
  feeOptionDescription: {
    color: colors.mutedForeground,
    fontSize: typography.tiny,
    textAlign: 'center',
  },
  feeOptionDescriptionActive: {
    color: colors.primaryText,
  },
  modalDividerText: {
    color: colors.mutedForeground,
    fontSize: typography.small,
    textAlign: 'center',
  },
  feeInfo: {
    width: '100%',
    backgroundColor: colors.background,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing.md,
    gap: spacing.xs,
  },
  feeInfoLine: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  feeInfoLabel: {
    color: colors.mutedForeground,
    fontSize: typography.small,
  },
  feeInfoValue: {
    color: colors.foreground,
    fontSize: typography.body,
    fontWeight: '600',
  },
  feeInfoMeta: {
    color: colors.mutedForeground,
    fontSize: typography.tiny,
  },
  feeInfoSecondary: {
    color: colors.mutedForeground,
    fontSize: typography.tiny,
    textAlign: 'right',
  },
  sendErrorText: {
    width: '100%',
    marginTop: spacing.sm,
    color: colors.danger,
    fontSize: typography.small,
    textAlign: 'center',
  },
  sendSuccessText: {
    width: '100%',
    marginTop: spacing.sm,
    color: colors.primary,
    fontSize: typography.small,
    textAlign: 'center',
  },
  modalInput: {
    width: '100%',
    backgroundColor: colors.background,
    color: colors.foreground,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
    fontSize: typography.body,
  },
  modalPrimaryButton: {
    width: '100%',
    marginTop: spacing.sm,
    paddingVertical: spacing.sm,
    borderRadius: radius.md,
    backgroundColor: colors.primary,
    alignItems: 'center',
  },
  modalPrimaryButtonContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xs,
  },
  modalPrimaryButtonDisabled: {
    opacity: 0.6,
  },
  modalPrimaryButtonText: {
    color: colors.primaryText,
    fontWeight: '600',
    fontSize: typography.body,
  },
  modalClose: {
    marginTop: spacing.sm,
    alignSelf: 'stretch',
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
    borderRadius: radius.md,
    backgroundColor: colors.primary,
    alignItems: 'center',
  },
  modalCloseText: {
    color: colors.primaryText,
    fontWeight: '600',
    fontSize: typography.small,
  },
  headerButton: {
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.sm + spacing.xs,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.primary,
    backgroundColor: 'transparent',
    minHeight: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerIconButton: {
    paddingVertical: 0,
    paddingHorizontal: 0,
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerButtonDisabled: {
    opacity: 0.5,
  },
  headerButtonText: {
    color: colors.primary,
    fontWeight: '600',
    fontSize: typography.small,
  },
  outlineButton: {
    backgroundColor: 'transparent',
  },
  dangerButton: {
    borderColor: '#ffd000ff',
    backgroundColor: '#ffd000ea',
  },
  dangerButtonText: {
    color: '#000000',
    fontSize: typography.body,
    fontWeight: '600',
  },
  disclaimer: {
    textAlign: 'center',
    color: colors.mutedForeground,
    fontSize: typography.small,
  },
  feedback: {
    padding: spacing.md,
    borderRadius: radius.md,
  },
  feedbackSuccess: {
    backgroundColor: '#5050509c',
  },
  feedbackError: {
    backgroundColor: '#ac0707ea',
  },
  feedbackText: {
    color: colors.foreground,
    textAlign: 'center',
    fontSize: typography.small,
  },
  historyModalCard: {
    maxHeight: '80%',
    width: '100%',
    gap: spacing.sm,
  },
  historyList: {
    width: '100%',
    maxHeight: 320,
  },
  historyItem: {
    width: '100%',
    paddingVertical: spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    gap: spacing.xs,
  },
  historyItemHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  historyAmount: {
    fontSize: typography.body,
    fontWeight: '600',
  },
  historyAmountPositive: {
    color: colors.primary,
  },
  historyAmountNegative: {
    color: colors.danger,
  },
  historyStatus: {
    fontSize: typography.tiny,
    fontWeight: '600',
  },
  historyStatusCompleted: {
    color: colors.primary,
  },
  historyStatusPending: {
    color: colors.mutedForeground,
  },
  historyMeta: {
    fontSize: typography.tiny,
    color: colors.mutedForeground,
  },
  historyTxid: {
    fontSize: typography.tiny,
    color: colors.foreground,
  },
  historyLinkButton: {
    alignSelf: 'flex-start',
    paddingVertical: spacing.xs,
    paddingHorizontal: spacing.sm,
    borderRadius: radius.sm,
    backgroundColor: colors.primary,
  },
  historyLinkText: {
    color: colors.primaryText,
    fontWeight: '600',
    fontSize: typography.tiny,
  },
  historyEmptyText: {
    color: colors.mutedForeground,
    textAlign: 'center',
    fontSize: typography.small,
  },
  historyError: {
    color: colors.danger,
    textAlign: 'center',
    fontSize: typography.small,
  },
  historyActions: {
    flexDirection: 'row',
    gap: spacing.sm,
    width: '100%',
  },
  historyActionButton: {
    flex: 1,
    paddingVertical: spacing.sm,
    borderRadius: radius.md,
    backgroundColor: colors.primary,
    alignItems: 'center',
  },
  historyActionButtonText: {
    color: colors.primaryText,
    fontWeight: '600',
    fontSize: typography.small,
  },
  historyCloseButton: {
    flex: 1,
    paddingVertical: spacing.sm,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
  },
  historyCloseButtonText: {
    color: colors.foreground,
    fontWeight: '600',
    fontSize: typography.small,
  },
  signingStateContainer: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: spacing.lg,
    gap: spacing.md,
  },
  signingStateText: {
    color: colors.mutedForeground,
    fontSize: typography.small,
    textAlign: 'center',
    paddingHorizontal: spacing.md,
  },
});




